<?php

use Drupal\teak_shipping as m;

/**
 * @file
 * Defines an example shipping method for testing and development.
 */

/**
 * Implements hook_commerce_price_component_type_info().
 */
function teak_shipping_commerce_price_component_type_info() {
  return array(
    'teak_shipping_service_express' => array(
      'title' => t('Express delivery'),
      'weight' => 20,
    ),
  );
}

/**
 * Implements hook_commerce_shipping_method_info().
 */
function teak_shipping_commerce_shipping_method_info() {
  $shipping_methods = array();

  $shipping_methods['teak_shipping_method'] = array(
    'title' => t('Teak shipping method'),
    'description' => t('Defines a single flat rate service with a couple of service details.'),
  );

  return $shipping_methods;
}

/**
 * Implements hook_commerce_shipping_service_info().
 */
function teak_shipping_commerce_shipping_service_info() {
  $shipping_services = array();

  $shipping_services['teak_shipping_service'] = array(
    'title' => t('Teak shipping service'),
    'description' => t('A $20 flat rate service with express delivery available for an additional $15.'),
    'display_title' => t('Shipping'),
    'shipping_method' => 'teak_shipping_method',
    'price_component' => 'shipping',
    'callbacks' => array(
      'rate' => '_teak_shipping_rate',
      #'details_form' => 'teak_shipping_service_details_form',
      #'details_form_validate' => 'teak_shipping_service_details_form_validate',
      #'details_form_submit' => 'teak_shipping_service_details_form_submit',
    ),
  );

  return $shipping_services;
}

/**
 * Shipping service callback: returns a base price array for a shipping service
 * calculated for the given order.
 */
function _teak_shipping_rate($shipping_service, $order) {

  // Start with empty cost.
  $cost = array(
    'amount' => 0,
    'currency_code' => 'EUR',
    'data' => array(),
  );

  $dispatcher = new m\Dispatcher();
  $cents = $dispatcher->getShippingCost($order);

  if (is_numeric($cents)) {
    $cost['amount'] = $cents;
  }

  return $cost;
}
